#define LED_WIFI_PORT GPIOC
#define LED_WIFI_PIN GPIO15

#define LED_868_PORT GPIOC
#define LED_868_PIN GPIO14

#define LED_AUX_PORT GPIOC
#define LED_AUX_PIN GPIO13

#define RADIO_INT_PORT GPIOB
#define RADIO_INT_PIN GPIO8
